import os

TOKEN = os.getenv("TOKEN")
RETRIEVER_HOST = os.getenv("RETRIEVER_HOST")
GENERATOR_HOST = os.getenv("GENERATOR_HOST")
MODEL_NAME = os.getenv("MODEL_NAME")
GENERATOR_TYPE = os.getenv("GENERATOR_TYPE")

DATA_FOLDER = os.getenv("DATA_FOLDER")
TARGET_FIELD = os.getenv("TARGET_FIELD")

CHUNK_SIZE = os.getenv("CHUNK_SIZE")
CHUNK_SIZE = int(CHUNK_SIZE) if CHUNK_SIZE is not None else None

CHUNK_OVERLAP = os.getenv("CHUNK_OVERLAP")
CHUNK_OVERLAP = int(CHUNK_OVERLAP) if CHUNK_OVERLAP is not None else None

MODEL_NAME = os.getenv("MODEL_NAME")
RETRIEVER_PORT = os.getenv("RETRIEVER_PORT")
