repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  -   id: check-yaml
  -   id: end-of-file-fixer
  -   id: trailing-whitespace
  -   id: check-added-large-files
  -   id: check-merge-conflict

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 'v1.9.0'
  hooks:
  -   id: mypy
      additional_dependencies: ["types-requests", "pydantic>=1.10.4"]


- repo: https://github.com/hadolint/hadolint
  rev: v2.12.0
  hooks:
  -   id: hadolint-docker

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.3.4
  hooks:
  -   id: ruff
  -   id: ruff-format
