version: '3.8'
services:
  telegram:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - intra
    command: python3 -m src.servers.telegram_server


  retriever:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./data/ready:/data
      - ~/.cache/huggingface/hub:/.cache/huggingface/hub
      - ./data/faiss_indexes:/faiss_indexes
    environment:
      - HF_HOME=/.cache/huggingface/hub
      - HUGGINGFACE_HUB_CACHE=/.cache/huggingface/hub
    networks:
      - intra
    command: python3 -m src.servers.retriever_server --port 8000 --db-load-folder /faiss_indexes

networks:
  intra:
