[documents]
folder = "/data"
target_column = "text"
chunk_size = 700
chunk_overlap = 200

[retriever]
embedding_model = "BAAI/bge-m3"
rerank_model = "BAAI/bge-reranker-v2-m3"
normalize_embeddings = false

[telegram]
study_rooms = [
    232, 233, 234, 225, 226, 228, 334, 335, 336, 338, 326, 327, 328, 329, 330,
    433, 435, 425, 426, 427, 428, 429, 520, 521, 522, 512, 513, 514, 515, 612,
    613, 614, 606, 607, 608, 712, 713, 714, 715, 703, 704, 705, 706, 707, 708
]
prompt_template = """
Контекст: {context}\n\nИспользуя контекст ответь на вопрос не упоминая, \
что информация взята из контекста. \
Если в контексте нет ответа, ответь 'Нет информации'. Вопрос: {query}
"""
welcome_text = """
Привет! Я ассистент для студентов МИЭМ. Помогаю найти информацию \
о факультете и вузе по вашим вопросам. Напишите свой вопрос, и я найду ответ.\n \
Если хочешь узнать к какому корпусу принадлежит аудитория, введи /which_building <номер аудитория>.
"""
temperature = 0.0
repeat_penalty = 1.1
